kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-nfs-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi